### ISSUE TITLE
TODO: 

### ISSUE THREAD

**Issue by erindepew** [mccorkle/SEWebFE#3]
- [x] set up framework
- [x] add in immutable data 
- [ ] set up websockets for react 

Inventory Block 
- [x] input field and change name
- [x] checkboxes and toggle properties
- [ ] multiselect blocks
- [x] choose framework for graphs
- [ ] build tree chart of items in inventory

Control Panel and Inventory 
- [x] list of inventory blocks
- [ ] select all checkbox
- [x] search field to filter list of inventory blocks (update on type) 
- [ ] pagination
- [ ] refresh

Tabs
- [ ] Control Panel and Inventory
- [ ] Production manager with CTA

**Comment by mccorkle** [comment]
This looks complete, but I'd like to have a 15 minute call with you so that I can say what I think each of these means so that we can both know we are aligned.

One question I have for you -- is on the registering of new grids / notifications -- where is that data stored?  Are you storing local in browser?  Do I need to build a backend service to store them?  

I don't think we spoke about login / user profile questions as well (and I don't have any of that mocked up) so let me know what you are thinking about for multi-user and persistent data.
